# Generated by Django 3.1 on 2020-08-22 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_created_at'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='ThroughSavedRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('saved_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.savedrecipe')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('saved_recipe', 'recipe')},
            },
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='recipes',
            field=models.ManyToManyField(through='users.ThroughSavedRecipe', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
