version: '3'

services:
  masak_db:
    container_name: masak_db
    image: postgres:12-alpine
    environment: 
        - POSTGRES_DB=masak2
        - POSTGRES_USER=masak2
        - POSTGRES_PASSWORD=masak
    ports:
      - 5432:5432

  masak_web:
    container_name: masak_web
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: poetry run masak2/manage.py runserver 0:80
    volumes:
      - ../:/app
    environment: 
        - DJANGO_SECRET_KEY=abc123
        - POSTGRES_DB=masak2
        - POSTGRES_USER=masak2
        - POSTGRES_PASSWORD=masak
        - DB_HOST=masak_db
        - DJANGO_DEBUG=yes?no?maybe?IDK
        - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - masak_db
    ports:
      - 8000:80
