version: "3"

services:
  masak_db:
    container_name: masak_db
    image: postgres:12-alpine
    env_file:
      - ../.env
    ports:
      - 5432:5432

  masak_web:
    container_name: masak_web
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: poetry run /app/masak2/manage.py runserver 0:80
    volumes:
      - ../:/app
    env_file:
      - ../.env
    depends_on:
      - masak_db
    ports:
      - 8000:80
