# Generated by Django 3.0.8 on 2020-08-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.FileField(blank=True, default='', upload_to='tags'),
        ),
    ]
