# Generated by Django 3.0.8 on 2020-07-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('IMG', 'image'), ('VID', 'vid')], default='IMG', max_length=255),
        ),
    ]
