# Generated by Django 3.0.6 on 2020-05-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_make_unit_not_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
