# Generated by Django 3.0.8 on 2020-08-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('recipes', '0002_auto_20200714_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(related_name='recipes', to='tags.Tag'),
        ),
    ]
