# Generated by Django 3.0.8 on 2020-08-14 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_add_tags_to_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
