# Generated by Django 3.0.8 on 2020-07-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_make_ingredient_name_and_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientname',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='ingredientunit',
            options={'ordering': ('name',)},
        ),
    ]
